-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."gigs" add column "isDeleted" boolean
--  not null default 'false';
