-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."profile_verfication" add column "visual_verification" text
--  null;
