-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."User_chat" add column "is_admin" boolean
--  null default 'false';
