-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."friendlist" add column "strength_friend" text
--  null default 'good';
